name       : shiboken2
version    : 5.15.10
release    : 10
source     :
    - https://download.qt.io/official_releases/QtForPython/pyside2/PySide2-5.15.10-src/pyside-setup-opensource-src-5.15.10.tar.xz : 2af691d3613a41f83a60439b46568fc2c696dbfae42f7cd7b07152d115ead33a
license    :
    - GPL-2.0-or-later
    - LGPL-3.0-or-later
component  : programming.python
summary    : Shiboken generates bindings for C++ libraries using CPython source code
description: |
    PySide2 is the official Python module from the Qt for Python project, which provides access to the complete Qt5 framework
clang      : yes
builddeps  :
    - pkgconfig(Qt5XmlPatterns)
    - pkgconfig(libxslt)
    - pkgconfig(python3)
rundeps    :
    - devel :
        - python3-devel
setup      : |
    cd sources/shiboken2
    %cmake_ninja -DBUILD_TESTS=OFF -DUSE_PYTHON_VERSION=3
build      : |
    cd sources/shiboken2
    %ninja_build
install    : |
    pushd sources/shiboken2
    %ninja_install
    popd

    rm -f $installdir/usr/bin/shiboken_tool.py

    python3 setup.py egg_info --build-type=shiboken2
    cp -r shiboken2.egg-info $installdir/$(python3 -c "import site; print(site.getsitepackages()[0])")
